global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "Post_app_api_metrics"
    metrics_path: /metrics
    static_configs:
      - targets: ["host.docker.internal:443"]
    scheme: https
    tls_config:
      insecure_skip_verify: true