version: '3.8'

services:
  db:
    container_name: Database_PostApp
    image: mysql:8.3.0
    ports:
      - "3306:3306"  # Porta padrão do MySQL
    environment:
      MYSQL_ROOT_PASSWORD: passWord01  # Define a senha do usuário root
      MYSQL_DATABASE: Db_PostApp
    networks:
      - my_network
      
  prometheus:
    container_name: Prometheus
    build: 
      context: ./prometheus
      dockerfile: Dockerfile
    ports:
      - "9090:9090"  # Porta do Prometheus
    networks:
      - my_network
      
  grafana:
    container_name: Grafana
    build:
      context: ./grafana
      dockerfile: Dockerfile
      args:
        version: 1
    image: grafana-local
    ports:
      - 3000:3000 # Porta do Grafana
    networks:
      - my_network
  
  api:
    container_name: API_PostApp
    build:
      context: .
      dockerfile: .docker/Dockerfile
    depends_on:
      - db    
    ports:
      - "8080:80"  # Porta exposta para acessar a API
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker  # Define o ambiente de execução da API
      - ConnectionStrings__MysqlConnection=Server=db;Port=3306;Uid=root;Database=Db_PostApp;Pwd=passWord01;
    networks:
      - my_network

  nginx:
    container_name: nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "443:443" # Porta do nginx
    depends_on:
      - api
    networks:
      - my_network

networks:
  my_network:
